In [1]:
import numpy as np

In [2]:
myarr= np.array([[3,6,7,32]],np.int32)

In [3]:
myarr

array([[ 3,  6,  7, 32]], dtype=int32)

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape


(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0,1]=45

In [8]:
myarr[0,1]


45

# Array Creation: Conversion from other python structutre

In [10]:
listarray= np.array([[1,2,3],[5,8,5],[0,3,1]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [12]:
listarray.dtype

dtype('int64')

In [13]:
listarray.shape

(3, 3)

In [15]:
 listarray.size

9

In [17]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [18]:
zeros= np.zeros((2,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
rng=np.arange(15)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspace=np.linspace(1,5,12)

In [26]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [29]:
emp= np.empty((4,6))  # random values

In [30]:
emp

array([[1.08619285e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 4.94065646e-324, 0.00000000e+000]])

In [34]:
emp_like=np.empty_like(lspace)

In [35]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [38]:
ide= np.identity(45) #identity unit matrixmatrix

In [39]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
ide.shape

(45, 45)

In [42]:
arr=np.arange(99)

In [45]:
arr= arr.reshape(3,33)

In [46]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [47]:
arr=arr.ravel()

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
x=[[1,2,3],[2,3,4],[5,6,7]]

In [51]:
ar=np.array(x)

In [52]:
ar

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [53]:
ar.sum(axis=0)

array([ 8, 11, 14])

In [54]:
ar.sum(axis=1)

array([ 6,  9, 18])

In [59]:
ar.T

array([[1, 2, 5],
       [2, 3, 6],
       [3, 4, 7]])

In [60]:
ar.flat

In [61]:
for item in ar.flat:
    print(item)

1
2
3
2
3
4
5
6
7


In [63]:
ar.ndim #no. of dimensions

2

In [65]:
ar.size

9

In [67]:
ar.nbytes

72

In [71]:
one= np.array([1,2,3,4,5])

In [73]:
one.argmax() #index of max

4

In [74]:
one.argmin()

0

In [77]:
one.argsort() #index to sort the array of indices

array([0, 1, 2, 3, 4])

In [95]:
ar

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [96]:
ar.argmin()

0

In [97]:
ar.argmax()

8

In [98]:
ar.argmax(axis=0)

array([2, 2, 2])

In [100]:
ar.argmax(axis= 1)

array([2, 2, 2])

In [101]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [102]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [104]:
ar.ravel()

array([1, 2, 3, 2, 3, 4, 5, 6, 7])

In [105]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [106]:
ar

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [108]:
ar2=np.array([[1, 4, 3],
       [2, 0, 4],
       [5, 9, 7]])

In [109]:
ar+ar2

array([[ 2,  6,  6],
       [ 4,  3,  8],
       [10, 15, 14]])

In [110]:
ar*ar2

array([[ 1,  8,  9],
       [ 4,  0, 16],
       [25, 54, 49]])

In [111]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131]])

In [113]:
ar.sum()

33

In [114]:
ar.min()

1

In [115]:
ar

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [117]:
type(np.where(ar>5))

tuple

In [118]:
np.count_nonzero(ar)

9

In [119]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [120]:
import sys

In [122]:
py_ar=[1,2,5]

In [123]:
np_ar=np.array(py_ar)

In [124]:
sys.getsizeof(1)*len(py_ar)

84

In [125]:
np_ar.itemsize*np_ar.size

24